# Generated by Django 3.2.9 on 2021-11-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.TextField(verbose_name=15)),
                ('description', models.TextField(verbose_name=32)),
                ('barcode', models.TextField(verbose_name=255)),
            ],
        ),
    ]
