# Generated by Django 3.2.9 on 2021-11-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='barcode',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='barang',
            name='description',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='barang',
            name='part_number',
            field=models.CharField(max_length=15),
        ),
    ]
