# Generated by Django 3.2.9 on 2021-11-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_alter_barang_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='part_number_customer',
            field=models.CharField(default='-', max_length=18),
            preserve_default=False,
        ),
    ]
