# Generated by Django 3.2.9 on 2021-11-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_rencanakirim_rencanakirimdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='rencanakirimdetail',
            name='nomor_line',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
