# Generated by Django 3.2.9 on 2021-11-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_rencanakirimdetail_nomor_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='rencanakirim',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('SC', 'Scanned')], default='OP', max_length=2),
        ),
    ]
