# Generated by Django 3.2.9 on 2021-11-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_rencanakirim_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rencanakirimdetail',
            name='qty',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
