# Generated by Django 3.2.9 on 2021-11-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0009_auto_20211117_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rencanakirim',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Scanned', 'Scanned')], default='Open', max_length=7),
        ),
    ]
