# Generated by Django 3.2.9 on 2021-11-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0012_alter_rencanakirim_nomor_sj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rencanakirim',
            name='nomor_sj',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
