# Generated by Django 3.2.9 on 2022-08-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0013_alter_rencanakirim_nomor_sj'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='color_code',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='barang',
            name='position_code',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
