# Generated by Django 3.2.9 on 2022-09-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0014_auto_20220802_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='qty_per_box',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
