# Generated by Django 3.2.9 on 2022-11-02 04:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0015_barang_qty_per_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='rencanakirim',
            name='cycle',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='barang',
            name='color_code',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
