# Generated by Django 4.1.3 on 2022-11-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0017_rename_nomor_line_rencanakirimdetail_no_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='position_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
