# Generated by Django 4.1.3 on 2022-11-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0018_alter_barang_position_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='color_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='position_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
