# Generated by Django 4.1.3 on 2022-11-14 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0019_alter_barang_color_code_alter_barang_position_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rencanakirim',
            name='jam',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='qty_per_box',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rencanakirim',
            name='tanggal',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Pengiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_pengiriman', models.IntegerField()),
                ('waktu_kirim', models.DateTimeField()),
                ('rencana_kirim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.rencanakirim')),
            ],
        ),
    ]
