# Generated by Django 4.1.3 on 2022-11-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0020_rencanakirim_jam_alter_barang_qty_per_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rencanakirim',
            name='tanggal',
            field=models.DateTimeField(),
        ),
    ]
