# Generated by Django 4.1.3 on 2022-11-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0021_alter_rencanakirim_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rencanakirim',
            name='tanggal',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
