# Generated by Django 4.1.3 on 2022-11-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0022_alter_rencanakirim_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rencanakirim',
            name='tanggal',
            field=models.DateField(),
        ),
    ]
