# Generated by Django 4.1.3 on 2022-11-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0023_alter_rencanakirim_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rencanakirim',
            name='nomor_sj',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
