# Generated by Django 4.1.3 on 2022-11-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0027_alter_barang_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='barcode',
            field=models.TextField(blank=True),
        ),
    ]
