# Generated by Django 4.1.3 on 2022-11-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0028_alter_barang_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rencanakirim',
            name='nomor_sj',
            field=models.CharField(max_length=7),
        ),
    ]
