# Generated by Django 4.1.3 on 2022-11-30 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0029_alter_rencanakirim_nomor_sj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rencanakirimdetail',
            name='barang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barang', to='scanner.barang'),
        ),
        migrations.AlterField(
            model_name='rencanakirimdetail',
            name='rencana_kirim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rencanakirim', to='scanner.rencanakirim'),
        ),
    ]
