# Generated by Django 4.1.3 on 2022-12-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0030_alter_rencanakirimdetail_barang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='part_number',
            field=models.CharField(max_length=18),
        ),
    ]
