# Generated by Django 4.1.3 on 2022-12-02 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0031_alter_barang_part_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='part_number',
        ),
    ]
