# Generated by Django 4.1.3 on 2022-12-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0032_remove_barang_part_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rencanakirim',
            name='nomor_sj',
        ),
        migrations.AddField(
            model_name='barang',
            name='part_number',
            field=models.CharField(default='abus', max_length=18),
            preserve_default=False,
        ),
    ]
