# Generated by Django 4.1.3 on 2022-12-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0033_remove_rencanakirim_nomor_sj_barang_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rencanakirimdetail',
            name='qty',
            field=models.CharField(max_length=4),
        ),
    ]
