# Generated by Django 4.1.3 on 2022-12-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0033_rencanakirimdetail_box_scanned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='qty_per_box',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
